# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, verbose_name='公司名称')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('linkname', models.CharField(max_length=20, verbose_name='联系人')),
                ('phone', models.IntegerField(verbose_name='联系电话')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('desc', models.TextField(verbose_name='备注')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '供应商管理',
                'verbose_name_plural': '供应商管理',
            },
        ),
    ]
