# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-05 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetNum', models.CharField(default='', max_length=128, verbose_name='资产编号')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='品牌')),
                ('config', models.CharField(default='', max_length=128, verbose_name='配置')),
                ('buyDate', models.DateField(verbose_name='购买日期')),
                ('warrantyDate', models.DateField(verbose_name='到保日期')),
                ('status', models.IntegerField(choices=[(1, '闲置'), (2, '在用'), (3, '维修'), (4, '报废')], default=1, verbose_name='资产状态')),
                ('desc', models.TextField(default='')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型名称', max_length=30, verbose_name='类型名称')),
                ('level', models.IntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], help_text='类型级别', verbose_name='类型级别')),
                ('status', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, help_text='所属', null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.AssetType', verbose_name='所属')),
            ],
            options={
                'verbose_name': '资产类型',
                'verbose_name_plural': '资产类型',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50, verbose_name='客户单位')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('name', models.CharField(max_length=20, verbose_name='联系人')),
                ('phone', models.CharField(max_length=30, verbose_name='联系电话')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '客户管理',
                'verbose_name_plural': '客户管理',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=30, verbose_name='设备编号')),
                ('equipment_model', models.CharField(default='', max_length=50, verbose_name='设备型号')),
                ('buy_date', models.DateField(verbose_name='购买日期')),
                ('warranty_date', models.DateField(verbose_name='质保日期')),
                ('config_desc', models.TextField(blank=True, null=True, verbose_name='配置说明')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.Customer', verbose_name='客户信息')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型名称', max_length=30, verbose_name='类型名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, verbose_name='公司名称')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('linkname', models.CharField(max_length=20, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '供应商管理',
                'verbose_name_plural': '供应商管理',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.EquipmentType', verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.Supplier', verbose_name='分销商'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assetType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.AssetType', verbose_name='资产类型'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用人'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Supplier', verbose_name='供应商'),
        ),
    ]
