# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-05 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='记录内容')),
                ('is_reminding', models.BooleanField(default=False, verbose_name='邮件消息提醒')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '设备管理', 'verbose_name_plural': '设备管理'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='service_info',
            field=models.ManyToManyField(blank=True, null=True, to='adm.ServiceInfo', verbose_name='服务记录'),
        ),
    ]
