# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
