# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20180505_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='service_info',
            field=models.ManyToManyField(blank=True, to='adm.ServiceInfo', verbose_name='服务记录'),
        ),
    ]
