# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20171220_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='联系电话'),
        ),
    ]
