# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20171220_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
