# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-05 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20180505_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
    ]
