# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_serviceinfo_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='accounting',
            field=models.BooleanField(default=False, verbose_name='费用核算状态'),
        ),
    ]
