# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_auto_20171220_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='资产类型', max_length=30, verbose_name='资产类型')),
                ('code', models.CharField(help_text='类型编码', max_length=30, verbose_name='类型编码')),
                ('code_type', models.IntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], help_text='类型级别', verbose_name='类型级别')),
                ('status', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('parent_code', models.ForeignKey(blank=True, help_text='所属', null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.AssetType', verbose_name='所属')),
            ],
            options={
                'verbose_name': '资产类型',
                'verbose_name_plural': '资产类型',
            },
        ),
    ]
