# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_equipment_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20, verbose_name='操作人')),
                ('desc', models.CharField(max_length=80, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='assettype',
            options={'verbose_name': '资产类型'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '分销商管理', 'verbose_name_plural': '分销商管理'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='config',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='level',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='status',
        ),
        migrations.AddField(
            model_name='asset',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='客户信息'),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(default='', max_length=30, verbose_name='型号'),
        ),
        migrations.AddField(
            model_name='asset',
            name='operator',
            field=models.CharField(default='', max_length=20, verbose_name='入库人'),
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='asset',
            name='warehouse',
            field=models.CharField(choices=[('0', '南京'), ('1', '苏州')], default='1', max_length=20, verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.AssetType', verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='desc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用人'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[('0', '闲置'), ('1', '在用'), ('2', '维修'), ('3', '报废'), ('4', '售出')], default='1', verbose_name='资产状态'),
        ),
        migrations.AddField(
            model_name='assetlog',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Asset', verbose_name='资产'),
        ),
    ]
