# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_assettype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettype',
            old_name='parent_code',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(help_text='类型名称', max_length=30, verbose_name='类型名称'),
        ),
    ]
