# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_auto_20171220_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettype',
            old_name='code_type',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='code',
        ),
    ]
