# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_auto_20180531_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlog',
            name='desc',
            field=models.TextField(default='', verbose_name='备注'),
        ),
    ]
