# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0008_auto_20180428_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetNum', models.CharField(default='', max_length=128, verbose_name='资产编号')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='品牌')),
                ('config', models.CharField(default='', max_length=128, verbose_name='配置')),
                ('buyDate', models.DateField(verbose_name='购买日期')),
                ('warrantyDate', models.DateField(verbose_name='到保日期')),
                ('status', models.IntegerField(choices=[(1, '闲置'), (2, '在用'), (3, '维修'), (4, '报废')], default=1, verbose_name='资产状态')),
                ('desc', models.TextField(default='')),
                ('assetType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.AssetType', verbose_name='资产类型')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=20, verbose_name='设备编号')),
                ('equipment_model', models.CharField(default='', max_length=20, verbose_name='设备型号')),
                ('buy_date', models.DateField(verbose_name='购买日期')),
                ('warranty_date', models.DateField(verbose_name='到保日期')),
                ('config_desc', models.TextField(default='', verbose_name='配置说明')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Customer', verbose_name='客户信息')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型名称', max_length=30, verbose_name='类型名称')),
                ('status', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.EquipmentType', verbose_name='设备类型'),
        ),
    ]
