# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_auto_20180430_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='status',
        ),
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Supplier', verbose_name='供应商'),
        ),
    ]
