# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_auto_20180430_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='config_desc',
            field=models.TextField(blank=True, null=True, verbose_name='配置说明'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warranty_date',
            field=models.DateField(verbose_name='质保日期'),
        ),
    ]
