# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-02 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_auto_20180501_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='dist_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='分销商联系人'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='dist_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='分销商联系电话'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='distributors',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='分销商'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Supplier', verbose_name='供应商'),
        ),
    ]
