# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 06:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0005_equipment_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkListRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[(2, '派发'), (3, '执行'), (4, '确认'), (5, '退回')], max_length=10, verbose_name='记录类型')),
                ('content', models.CharField(default='', max_length=500, verbose_name='记录内容')),
                ('file_content', models.FileField(default='', upload_to='file_folder/%Y/%m', verbose_name='实施文档')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='记录时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='工单号')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('type', models.CharField(choices=[(0, '初次安装'), (1, '售后现场'), (2, '远程支持'), (3, '售前支持')], default=0, max_length=10, verbose_name='工单类型')),
                ('status', models.CharField(choices=[(0, '新建-保存'), (1, '提交-等待审批'), (2, '已审批-等待执行'), (3, '已执行-等待确认'), (4, '确认-完成'), (5, '退回')], default=0, max_length=10, verbose_name='工单状态')),
                ('do_time', models.DateTimeField(default='', verbose_name='安排时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('content', models.CharField(max_length=300, verbose_name='工单内容')),
                ('file_content', models.FileField(default='', upload_to='file_folder/%Y/%m', verbose_name='项目资料')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Customer', verbose_name='客户信息')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposer', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='接单人')),
            ],
            options={
                'verbose_name': '工单信息',
                'verbose_name_plural': '工单信息',
            },
        ),
        migrations.AddField(
            model_name='worklistrecord',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.WorkOrder', verbose_name='工单信息'),
        ),
    ]
