# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-26 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0002_auto_20180524_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[(2, '派发'), (3, '执行'), (4, '确认'), (5, '退回')], max_length=10, verbose_name='记录类型')),
                ('content', models.CharField(default='', max_length=500, verbose_name='记录内容')),
                ('file_content', models.FileField(default='', upload_to='file_folder/%Y/%m', verbose_name='实施文档')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
            },
        ),
        migrations.RemoveField(
            model_name='worklistrecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worklistrecord',
            name='work_order',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('0', '退回'), ('1', '新建-保存'), ('2', '提交-等待审批'), ('3', '已审批-等待执行'), ('4', '已执行-等待确认'), ('5', '完成')], default='0', max_length=10, verbose_name='工单状态'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='type',
            field=models.CharField(choices=[('0', '初次安装'), ('1', '售后现场'), ('2', '远程支持'), ('3', '售前支持')], default='0', max_length=10, verbose_name='工单类型'),
        ),
        migrations.DeleteModel(
            name='WorkListRecord',
        ),
        migrations.AddField(
            model_name='workorderrecord',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.WorkOrder', verbose_name='工单信息'),
        ),
    ]
