# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20180526_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderrecord',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m', verbose_name='实施文档'),
        ),
        migrations.AlterField(
            model_name='workorderrecord',
            name='record_type',
            field=models.CharField(choices=[('0', '退回'), ('1', '派发'), ('2', '执行'), ('3', '确认')], max_length=10, verbose_name='记录类型'),
        ),
    ]
