# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20180527_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m', verbose_name='项目资料'),
        ),
        migrations.AlterField(
            model_name='workorderrecord',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m', verbose_name='实施文档'),
        ),
    ]
