# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20180527_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('0', '工单已退回'), ('1', '新建-保存'), ('2', '提交-等待审批'), ('3', '已审批-等待执行'), ('4', '已执行-等待确认'), ('5', '工单已完成')], default='0', max_length=10, verbose_name='工单状态'),
        ),
    ]
